homeserver:
  address: http://synapse:8008
  domain: matrix.fathertkt.uk
  software: standard
appservice:
  address: http://meta:29319
  hostname: 0.0.0.0
  port: 29319
  database:
    type: postgres
    uri: postgres://synapse:1234@db/mautrix_meta?sslmode=disable
  id: meta
  bot:
    username: pmb-bot
    displayname: Instagram Bridge Bot
    avatar: mxc://maunium.net/NeXNQarUbrlQBiwhd5226463
  as_token: ''
  hs_token: ''
bridge:
  username_template: meta_{}
  displayname_template: '{displayname} (IG)'
  personal_filtering_spaces: false
  delivery_receipts: false
  message_status_events: false
  message_error_notices: false
  rest_api: false
  encryption:
    allow: true
    default: true
    require: false
    appservice: false
    client: false
  permissions:
    '*': admin
hacky_config_migrator: true
network:
  hacky_legacy_config_migrator: true
